"""decision_db

Revision ID: 530e942bffd9
Revises: 10651a6d92bd
Create Date: 2026-03-07 12:59:57.564898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530e942bffd9'
down_revision: Union[str, Sequence[str], None] = '10651a6d92bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_identity', sa.String(), nullable=False),
    sa.Column('semantic_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('governance_status', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('execution_latency_ms', sa.Float(), nullable=True),
    sa.Column('cryptographic_receipt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['pricing_rule_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_agent_identity'), 'decision_records', ['agent_identity'], unique=False)
    op.create_index(op.f('ix_decision_records_cryptographic_receipt'), 'decision_records', ['cryptographic_receipt'], unique=True)
    op.create_index(op.f('ix_decision_records_evaluated_at'), 'decision_records', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_decision_records_governance_status'), 'decision_records', ['governance_status'], unique=False)
    op.create_index(op.f('ix_decision_records_tenant_id'), 'decision_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_records_tenant_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_governance_status'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_evaluated_at'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_cryptographic_receipt'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_agent_identity'), table_name='decision_records')
    op.drop_table('decision_records')
    # ### end Alembic commands ###
