import urllib.request
import urllib.parse
import urllib.error
import json
import os
from typing import Dict, Any, Optional

class TempusClient:
    """
    Official Python Client for Tempus Decision Database (DDB).
    Provides a seamless interface for AI Agents to request immutable decisions.
    """

    def __init__(self, api_url: str = "http://localhost:8001/api/v1", api_key: Optional[str] = None):
        """
        Initialize the Tempus Decision Database client.
        
        Args:
            api_url: The base URL of the Tempus Engine API.
            api_key: The authentication key (can also be read from TEMPUS_API_KEY env var).
        """
        self.api_url = api_url.rstrip('/')
        self.api_key = api_key or os.environ.get("TEMPUS_API_KEY", "")

    def _make_request(self, endpoint: str, method: str = "GET", data: Optional[Dict] = None) -> Dict[str, Any]:
        """Internal helper to make HTTP requests."""
        url = f"{self.api_url}{endpoint}"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}"
        }
        
        req_data = None
        if data:
            req_data = json.dumps(data).encode('utf-8')
            
        req = urllib.request.Request(url, data=req_data, headers=headers, method=method)
        
        try:
            with urllib.request.urlopen(req) as response:
                result = json.loads(response.read().decode('utf-8'))
                return result
        except urllib.error.HTTPError as e:
            error_msg = e.read().decode('utf-8')
            raise RuntimeError(f"Tempus API Error [{e.code}]: {error_msg}")
        except Exception as e:
            raise RuntimeError(f"Connection to Tempus API failed: {str(e)}")


    def request_decision(self, agent_id: str, rule_name: str, context: Dict[str, Any], input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Request a governed decision from the Tempus Engine.
        
        Args:
            agent_id: Identifier of the AI agent requesting the decision.
            rule_name: The governance policy rule to evaluate against.
            context: Contextual data (e.g., semantic retrieval results).
            input_data: The deterministic input payload to be evaluated.
            
        Returns:
            A dictionary containing the decision outcome and the Cryptographic Receipt.
        """
        payload = {
            "agent_id": agent_id,
            "rule_name": rule_name,
            "context": context,
            "input_data": input_data
        }
        
        return self._make_request("/govern/decide", method="POST", data=payload)


    def audit_receipt(self, receipt_hash: str) -> Dict[str, Any]:
        """
        Audit an existing decision mathematically to verify its integrity.
        
        Args:
            receipt_hash: The cryptographic HMAC-SHA256 receipt generated by `request_decision`.
            
        Returns:
            A dictionary confirming the integrity status of the record.
        """
        return self._make_request(f"/govern/audit/{receipt_hash}", method="GET")

